<?PHP
echo 15;
echo"<br>";
print (1.1);
echo"<br>";
echo "cokkies";
echo"<br>";
print(TRUE);
echo"<br>";
echo "zde spojuji jeden řetězec"." s druhým řetězcem";
echo"<br>";
echo "<img src=\"art.jpg\" alt=\"mno\">";
echo "<br>";
echo "\\";
echo "<br>";
echo "OPERÁTORY: ";
echo "<br>";
        $a = 3;
        $b = 5;
        echo "a=" . $a . "<br>" . "b=" . $b . "<br>";
        echo "sčítání,odčítání,děleno,krát";
        var_dump($a + $b);
        echo"<br>";
        var_dump($a - $b);
        echo"<br>";
        var_dump($a / $b);
        echo"<br>";
        var_dump($a * $b);
        echo"<br>"."<br>";
        echo "a++,++a, a--,--a, a+=b a-=b, a*=b,a/=b";
        echo"<br>";
        var_dump($a++);
        $a = 3;
        echo"<br>";
        var_dump(++$a);
        $a = 3;
        echo"<br>";
        var_dump($a--);
        $a = 3;
        echo"<br>";
        var_dump(--$a);
        $a = 3;
        echo"<br>";
        var_dump($a += $b);
        $a = 3;
        echo"<br>";
        var_dump($a -= $b);
        $a = 3;
        echo"<br>";
        var_dump($a *= $b);
        $a = 3;
        echo"<br>";
        var_dump($a /= $b);
        $a = 3;
        echo"<br>" . "<br>";
        echo "a==b,a!=b, a>b, a < b" . "<br>";
        var_dump($a == $b);
        echo"<br>";
        var_dump($a != $b);
        echo"<br>";
        var_dump($a > $b);
        echo"<br>";
        var_dump($a < $b);
        echo"<br>"."<br>";
        echo "a||b, a&&b, !a" . "<br>";
        $a = 0;
        $b = 1;
        echo "a=" . $a . "<br>" . "b=" . $b;
        echo"<br>";
        var_dump($a || $b);
        echo"<br>";
        var_dump($a && $b);
        echo "<br>";
        var_dump(!$a);
?>